// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEFvQrRFxiYpYdrUINdPZ3KLeXfTopSVo',
    appId: '1:804369813454:web:f0aedf60e7a29d5a82259f',
    messagingSenderId: '804369813454',
    projectId: 'fres-ia',
    authDomain: 'fres-ia.firebaseapp.com',
    databaseURL: 'https://fres-ia-default-rtdb.firebaseio.com',
    storageBucket: 'fres-ia.appspot.com',
    measurementId: 'G-1V2R2LEBXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX8wce4npMfAMWXJkNo2QxhKMrSQVvkTE',
    appId: '1:804369813454:android:ace95bac3b27a2e182259f',
    messagingSenderId: '804369813454',
    projectId: 'fres-ia',
    databaseURL: 'https://fres-ia-default-rtdb.firebaseio.com',
    storageBucket: 'fres-ia.appspot.com',
  );
}
